services:
  - type: web
    name: ecommerce
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    envVars:
      PYTHON_VERSION: 3.10.14
